import{a as p,S as m,i as a}from"./assets/vendor-BDlA6vKe.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();class y{constructor(){this.searchQuery="",this.page=1,this.PER_PAGE=40}async fetchGallery(){const e={method:"get",url:"https://pixabay.com/api/",params:{key:"51318694-35374bea804290f3a0783253d",q:this.searchQuery,image_type:"photo",orientation:"horizontal",safesearch:!0,page:this.page,per_page:this.PER_PAGE}};try{const s=await p(e);return this.incrementPage(),s.data}catch(s){throw console.error("❌ Error fetching data from Pixabay:",s),s}}incrementPage(){this.page+=1}resetPage(){this.page=1}get query(){return this.searchQuery}set query(e){this.searchQuery=e}}const i={searchForm:document.querySelector(".form"),galleryContainer:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")},g=new m(".gallery a",{captionsData:"alt",captionDelay:250});function b(t){const e=t.map(({webformatURL:s,largeImageURL:l,tags:r,likes:o,views:n,comments:h,downloads:f})=>`
          <div class="photo-card">
            <a href="${l}">
              <img class="photo-img" src="${s}" alt="${r}" loading="lazy" />
            </a>
            <div class="info">
              <p class="info-item"><b>Likes</b> ${o}</p>
              <p class="info-item"><b>Views</b> ${n}</p>
              <p class="info-item"><b>Comments</b> ${h}</p>
              <p class="info-item"><b>Downloads</b> ${f}</p>
            </div>
          </div>`).join("");i.galleryContainer.insertAdjacentHTML("beforeend",e),g.refresh()}function L(){i.galleryContainer.innerHTML=""}function w(){var t;(t=document.querySelector(".preloader"))==null||t.classList.remove("is-hidden")}function P(){var t;(t=document.querySelector(".preloader"))==null||t.classList.add("is-hidden")}let u=0;const c=new y;i.searchForm.addEventListener("submit",S);i.loadMoreBtn.addEventListener("click",v);async function S(t){t.preventDefault(),L();const e=t.currentTarget.querySelector('input[name="searchQuery"]');if(!e){console.error('⛔️ Input [name="searchQuery"] not found');return}if(c.query=e.value.trim(),c.resetPage(),c.query===""){a.warning({message:"Please, fill the main field",position:"topRight"});return}u=0,await d()}async function v(){c.incrementPage(),await d()}async function d(){i.loadMoreBtn.classList.add("is-hidden"),w();try{const t=await c.fetchGallery(),{hits:e,total:s}=t;return e.length?(b(e),u+=e.length,u<s&&(a.success({message:`Hooray! Found ${s} images!`,position:"topRight"}),i.loadMoreBtn.classList.remove("is-hidden")),u>=s&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),e):(a.error({message:"Sorry, no images found.",position:"topRight"}),null)}catch(t){a.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("❌ Error fetching gallery:",t)}finally{P()}}
//# sourceMappingURL=index.js.map
