import{a as h,S as g,i as c}from"./assets/vendor-BDlA6vKe.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const y="51318694-35374bea804290f3a0783253d",L="https://pixabay.com/api/",b=40;async function v(e,o){const i={key:y,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:b};try{return(await h.get(L,{params:i})).data}catch(s){throw console.error("❌ Error fetching data from Pixabay:",s),s}}const a={searchForm:document.querySelector(".form"),galleryContainer:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")},w=new g(".gallery a",{captionsData:"alt",captionDelay:250});function S(e){const o=e.map(({webformatURL:i,largeImageURL:s,tags:t,likes:r,views:n,comments:p,downloads:m})=>`
          <div class="photo-card">
            <a href="${s}">
              <img class="photo-img" src="${i}" alt="${t}" loading="lazy" />
            </a>
            <div class="info">
              <p class="info-item"><b>Likes</b> ${r}</p>
              <p class="info-item"><b>Views</b> ${n}</p>
              <p class="info-item"><b>Comments</b> ${p}</p>
              <p class="info-item"><b>Downloads</b> ${m}</p>
            </div>
          </div>`).join("");a.galleryContainer.insertAdjacentHTML("beforeend",o),w.refresh()}function P(){a.galleryContainer.innerHTML=""}function E(){var e;(e=document.querySelector(".preloader"))==null||e.classList.remove("is-hidden")}function q(){var e;(e=document.querySelector(".preloader"))==null||e.classList.add("is-hidden")}let u="",d=1,l=0;a.searchForm.addEventListener("submit",M);a.loadMoreBtn.addEventListener("click",$);async function M(e){if(e.preventDefault(),u=e.currentTarget.elements.searchQuery.value.trim(),!u){c.warning({message:"Please, enter a search term",position:"topRight"});return}d=1,l=0,P(),await f()}async function $(){d+=1,await f()}async function f(){E(),a.loadMoreBtn.classList.add("is-hidden");try{const{hits:e,totalHits:o}=await v(u,d);if(e.length===0&&l===0){c.error({message:"No images found",position:"topRight"});return}S(e),l+=e.length,d===1&&c.success({message:`Hooray! Found ${o} images!`,position:"topRight"}),l<o?a.loadMoreBtn.classList.remove("is-hidden"):c.info({message:"You've reached the end of the search results.",position:"topRight"})}catch(e){c.error({message:"Failed to fetch images. Please try again later.",position:"topRight"}),console.error("❌ Error:",e)}finally{q()}}
//# sourceMappingURL=index.js.map
